services:
  docuxtract:
    build:
      context: . # Current directory, where the Dockerfile is located
    working_dir: /app
    env_file: .env
    environment:
      OLLAMA_HOST: ollama
      OLLAMA_PORT: 11434
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - ollama
    networks:
      - ollama-docker
    ports:
      - 8000:8000

  ollama:
    image: ollama/ollama:latest
    # hostname: http://ollama-container:11434/api/generate
    pull_policy: always
    tty: true
    restart: always
    ports:
      - 11434:11434
    environment:
      OLLAMA_HOST: 0.0.0.0
      MODEL: mistral:7b
    volumes:
      - ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ollama-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all

volumes:
  ollama:


networks:
  ollama-docker:
    external: false
