apiVersion: v1
kind: Namespace
metadata:
  name: docuxtract

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: docuxtract
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docuxtract-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: OLLAMA_HOST
              value: "http://ollama:11434"  # internal URL for Ollama container

      #   - name: ollama
      #     image: mistral-7b:latest  # replace with your Ollama image that includes the mistral:7b model
      #     imagePullPolicy: Never
      #     ports:
      #       - containerPort: 11434
      #     args: ["mistral:7b"]
      #     # resources:
      #     #   limits:
      #     #     nvidia.com/gpu: 1  # Requests one GPU; adjust based on requirements
      #     securityContext:
      #       capabilities:
      #         add: ["NET_ADMIN"]
      # # nodeSelector:
      # #   nvidia.com/gpu.present: "true"  # Ensures the pod is scheduled on nodes with GPUs

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: docuxtract
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: docuxtract
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: backend.example.com  # Replace with your domain or IP
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000